export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  EDITOR: "EDITOR",
  CUSTOMER: "CUSTOMER",
};

export const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.EDITOR];
export const SUPER_ADMIN_ONLY = [ROLES.SUPER_ADMIN];
